# @name tokenacc

// requisição de login
###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "user": "william",
    "pwd": "123"
}

// requisição para acessar rota protegida por token jwt
###
GET http://localhost:3000/auth/protectedExample HTTP/1.1
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5MzU0MTg2LCJleHAiOjE3MTkzNTc3ODZ9.N-Lbu31nacfSW_7NVPx7yqO8tpOYhmdmX_yJhknXx9s

// requisição para logout
###
POST http://localhost:3000/auth/logout HTTP/1.1
Content-Type: application/json